[package]
name = "mining-proxy"
version = "0.1.0"
authors = ["user"]
edition = "2018"

[dependencies]
async-channel = "1.5.1"
async-recursion = "0.3.2"
binary_sv2 = { path = "../../../protocols/v2/binary-sv2/binary-sv2" }
buffer_sv2 = { path = "../../../utils/buffer" }
codec_sv2 = { path = "../../../protocols/v2/codec-sv2", features = ["noise_sv2", "with_buffer_pool"] }
const_sv2 = { path = "../../../protocols/v2/const-sv2" }
futures = "0.3.19"
network_helpers = { path = "../../../utils/network-helpers", features = ["with_tokio","with_buffer_pool"] }
once_cell = "1.12.0"
roles_logic_sv2 = { path = "../../../protocols/v2/roles-logic-sv2" }
serde = { version = "1.0.89", features = ["derive", "alloc"], default-features = false }
tokio = { version = "1", features = ["full"] }
toml = { git = "https://github.com/diondokter/toml-rs", default-features = false, rev = "c4161aa" }
