[workspace]

members = [
    "protocols/v1",
    "protocols/v2/binary-sv2/serde-sv2",
    "protocols/v2/binary-sv2/no-serde-sv2/codec",
    "protocols/v2/binary-sv2/no-serde-sv2/derive_codec",
    "protocols/v2/binary-sv2/binary-sv2",
    "protocols/v2/noise-sv2",
    "protocols/v2/framing-sv2",
    "protocols/v2/codec-sv2",
    "protocols/v2/const-sv2",
    "protocols/v2/subprotocols/common-messages",
    "protocols/v2/subprotocols/template-distribution",
    "protocols/v2/subprotocols/mining",
    "protocols/v2/subprotocols/job-negotiation",
    "protocols/v2/sv2-ffi",
    "protocols/v2/roles-logic-sv2",
    "roles/v2/mining-proxy",
    "roles/v2/pool",
    "roles/v2/test-utils/mining-device",
    "roles/v2/test-utils/pool",
    "utils/network-helpers",
    "utils/buffer",
    "examples/sv1-client-and-server",
    "examples/sv1-to-sv2",
    "examples/ping-pong-with-noise",
    "examples/ping-pong-without-noise",
    "examples/interop-cpp",
    "examples/interop-cpp/template-provider/example-of-guix-build/quickcheck",
    "examples/interop-cpp/template-provider/example-of-guix-build/quickcheck_macros",
    "examples/template-provider-test",
    "experimental/coinbase-negotiator",
]
