[package]
name = "roles_logic_sv2"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.89", features = ["derive", "alloc"], default-features = false, optional = true}
binary_sv2 = {version = "0.1.3", path = "../../../protocols/v2/binary-sv2/binary-sv2", default-features = true }
common_messages_sv2 = { path = "../../../protocols/v2/subprotocols/common-messages", version = "0.1.3" }
mining_sv2 = { path = "../../../protocols/v2/subprotocols/mining", version = "0.1.0" }
template_distribution_sv2 = { path = "../../../protocols/v2/subprotocols/template-distribution", version = "0.1.3"}
job_negotiation_sv2 = { path = "../../../protocols/v2/subprotocols/job-negotiation", version = "0.1.0"}
const_sv2 = { version = "0.1.0", path = "../../../protocols/v2/const-sv2"}
framing_sv2 = { path = "../../../protocols/v2/framing-sv2" }
bitcoin = "0.27.1"
toml = {git = "https://github.com/diondokter/toml-rs", default-features = false, rev="c4161aa"}
general_utils_sv2 = { path = "../../../utils/general-utils-sv2"}


[features]
with_serde = [ "serde",
"binary_sv2/with_serde",
"common_messages_sv2/with_serde",
"template_distribution_sv2/with_serde",
"job_negotiation_sv2/with_serde",
"mining_sv2/with_serde"]
