on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Stratum V2

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - macos-latest
          - ubuntu-latest
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl

    steps:
      - name: Install stable toolchain & components
        uses: actions/checkout@v2
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Build ping-pong-with-noise example
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path examples/ping-pong-with-noise/Cargo.toml

      - name: Build ping-pong-without-noise example
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path examples/ping-pong-without-noise/Cargo.toml

      - name: Build sv1-client-and-server example
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path examples/sv1-client-and-server/Cargo.toml

      - name: Rust fmt lint
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Cargo clippy lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: Cargo clippy lint ping-pong-with-noise example
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path examples/ping-pong-with-noise/Cargo.toml -- -D warnings

      - name: Cargo clippy lint ping-pong-without-noise example
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path examples/ping-pong-without-noise/Cargo.toml -- -D warnings

      - name: Cargo clippy lint sv1-client-and-server example
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path examples/sv1-client-and-server/Cargo.toml -- -D warnings
